-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 13:45:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idcliente` INT NOT NULL,
  `cliente` VARCHAR(60) NULL,
  `nomecontato` VARCHAR(60) NULL,
  `endereco` VARCHAR(60) NULL,
  `cidade` VARCHAR(60) NULL,
  `pais` VARCHAR(60) NULL,
  `paiscodigo` VARCHAR(2) NULL,
  `regiao` VARCHAR(60) NULL,
  `cep` VARCHAR(45) NULL,
  `latitude` DECIMAL NULL,
  `longitude` DECIMAL NULL,
  `fax` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cupons` (
  `idcupom` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idfuncionario` INT NULL,
  `data` DATE NULL,
  `valorfrete` DECIMAL NULL,
  `empresafrete` VARCHAR(60) NULL,
  `dataentrega` DATE NULL,
  PRIMARY KEY (`idcupom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `idvendas` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NOT NULL,
  `quantidade` DECIMAL(10,10) NULL,
  `valor` DECIMAL(10,10) NULL,
  `desconto` DECIMAL(10,10) NULL,
  `custo` DECIMAL(10,10) NULL,
  `valorliquido` DECIMAL(10,10) NULL,
  `idcliente` INT NOT NULL,
  `idcupom` INT NOT NULL,
  INDEX `fk_vendas_clientes_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_vendas_Cupons1_idx` (`idcupom` ASC) VISIBLE,
  PRIMARY KEY (`idvendas`),
  CONSTRAINT `fk_vendas_clientes`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_Cupons1`
    FOREIGN KEY (`idcupom`)
    REFERENCES `mydb`.`cupons` (`idcupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
